spring:
  application:
    name: config #在eureka server 注册的服务名称为config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/greenHandChen/spring-cloud-demo.git
          search-paths: cloud-config-repo
  jackson:
      serialization:
        indent-output: true #美化JSON格式数据
server:
  port: 8888